spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: 1234
    url: jdbc:mariadb://localhost:3306/pandasaza_resource?characterEncoding=UTF-8&serverTimezone=UTC

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        default_batch_fetch_size: 1000
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: true

logging:
  level:
    org.hibernate.SQL: debug