server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    password: 1123
    url: jdbc:mariadb://localhost:3306/pandasaza?characterEncoding=UTF-8&serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
    username: root
  jackson:
    property-naming-strategy: SNAKE_CASE
  web:
    resources:
      add-mappings: true
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create
    properties:
      hiberate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

  profiles:
    include:
      - aws
      - credentials
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

cloud:
  aws:
    s3:
      bucket: coding-panda
    region:
      static: ap-northeast-2
    stack:
      auto: false
    credentials:
      #       AWS CLI에서 aws configure list 정보를 반영할건지 여부
      instanceProfile: true
