spring:
    datasource:
        driverClassName: org.mariadb.jdbc.Driver
        password: 1234
        url: jdbc:mariadb://localhost:3306/pandasaza_base?characterEncoding=UTF-8&serverTimezone=UTC
        username: root
    h2:
        console:
            enabled: true
            path: /h2-console
    jackson:
        property-naming-strategy: SNAKE_CASE

server:
    port: 8081


